Repository mskim0425/asap, pull requests merged in 2023-04, with the labels that each got.

#16 feat: 일별 총 출고량 계산로직
  be/.gradle/7.6.1/executionHistory/executionHistory.bin
  be/.gradle/7.6.1/executionHistory/executionHistory.lock
  be/.gradle/7.6.1/fileHashes/fileHashes.bin
  be/.gradle/7.6.1/fileHashes/fileHashes.lock
  be/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  be/.gradle/file-system.probe
  be/.idea/compiler.xml
  be/build.gradle
  be/src/main/java/asap/be/dto/MoneyDto.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
Labels: enhancement, BE

#21 feat: 대시보드 서비스 #4 #5 메서드 구현 완료
  .idea/workspace.xml
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/notification/Notification.java
  be/src/main/java/asap/be/domain/notification/NotificationType.java
  be/src/main/java/asap/be/dto/DashboardDto.java
  be/src/main/java/asap/be/dto/ProductUpdateDto.java
  be/src/main/java/asap/be/dto/RequestDto.java
  be/src/main/java/asap/be/repository/EmitterRepository.java
  be/src/main/java/asap/be/repository/NotificationRepository.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/EmitterMyBatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/NotificationService.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/resources/application.yml
Labels: enhancement, BE

#22 fix: 테스트코드
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/Stock.java
  be/src/main/java/asap/be/dto/EverythingDto.java
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/dto/ProductUpdateDto.java
  be/src/main/java/asap/be/dto/ReleaseStockDto.java
  be/src/main/java/asap/be/dto/RequestDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
Labels: BE

#24 fix: 상품 등록/입고/출고, 업데이트 쿼리 합침
  be/build.gradle
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/EditProductDto.java
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/dto/RequestDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/MainControllerRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/utils/ApiDocumentUtils.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: BE

#28 feat: businessLogicException + dummy data settings
  be/build.gradle
  be/src/main/java/asap/be/BeApplication.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/exception/BusinessLogicException.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
Labels: enhancement, BE

#31 feat: findall method
  be/.gitignore
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
Labels: enhancement, BE

#32 fix: insertOrUpdateStock, and feat findAllCntByPid
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/AllProductCntDto.java
  be/src/main/java/asap/be/dto/ReleaseStockDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/WarehouseMapper.xml
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: BE

#33 fix: 일별 상품 입고량 TOP10 버그 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/YearStatusDto.java
  be/src/main/java/asap/be/exception/BusinessLogicException.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/java/asap/be/utils/ApiDocumentUtils.java
Labels: bug, BE

#34 feat: findAll, findOne, restDocs
  be/.gitignore
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/DetailInfoDto.java
  be/src/main/java/asap/be/dto/EverythingPageDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: enhancement, BE

#35 fix: 상품별 최근 21일간 입/출고량 조회 디비 접근 줄임
  be/.gitignore
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/DashboardDto.java
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/dto/ProductCntDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/utils/Dummy.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: BE

#37 feat: new API working and changed some bugs
  be/.gitignore
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/repository/EmitterRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/static/docs/index.html
Labels: bug, enhancement, BE

#40 fix: 입고 출고 쿼리 구분 및 에러처리
  be/build.gradle
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/exception/ErrorResponder.java
  be/src/main/java/asap/be/exception/ErrorResponse.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/exception/GlobalExceptionAdvice.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
Labels: bug, BE

#41 fix: all the bugs but 3 of left
  be/src/main/java/asap/be/dto/DetailInfoDto.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/WarehouseMapper.xml
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: bug, enhancement, BE

#42 fix: 자잘한 버그 및 예외처리
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/exception/GlobalExceptionAdvice.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/WarehouseMapper.xml
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/java/asap/be/domain/WarehouseRepositoryTest.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: bug, BE

#43 feat: six new api and test codes
  be/build.gradle
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/DayMaxValueDto.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/WarehouseMapper.xml
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest2.java
Labels: BE

#45 fix: test errors
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest2.java
Labels: bug, BE

#46 fix: pId로 조회 -> pName 조회로 변경 및 버그 해결
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/NotificationService.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/controller/NotificationRestDocs.java
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: bug, BE

#47 feat: 검색데이터 API 추가와 테스트코드 수정
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/YearStatusDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/domain/DashBoardServiceImplTest2.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/utils/Dummy.java
Labels: enhancement, BE

#52 fix: 총재고,총입고,총출고량 조회 데이터 수정
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/controller/WarehouseRestDocs.java
  be/src/test/java/asap/be/dashboard/DashBoardServiceImplTest.java
  be/src/test/java/asap/be/dashboard/DashBoardServiceImplTest2.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/java/asap/be/utils/MainControllerConstants.java
Labels: bug, BE

#53 feat: 레디스 캐시 적용
  be/build.gradle
  be/src/main/java/asap/be/BeApplication.java
  be/src/main/java/asap/be/config/CacheConstant.java
  be/src/main/java/asap/be/config/RedisConfig.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
Labels: BE

#55 fix: 데이터 변경 시 레디스 캐시 삭제
  be/build.gradle
  be/src/main/java/asap/be/config/CacheConstant.java
  be/src/main/java/asap/be/config/RedisConfig.java
  be/src/main/java/asap/be/dto/MoneyDto.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
Labels: BE

#62 [FIX] dailyRecord && SSE
  asap/package-lock.json
  asap/package.json
  asap/public/index.html
  asap/src/Component/Chart/GeoChart.js
  asap/src/Component/SSE.js
  asap/src/Component/Top10.js
  asap/src/Pages/Dashboard.css
  asap/src/Pages/Dashboard.js
  asap/src/apis/GetAllProductNames.js
  asap/src/apis/GetDailyCheckByProductName.js
  asap/src/apis/GetDailyRecord.js
  asap/src/apis/GetMonthlyData.js
  asap/src/apis/GetTotalSales.js
  asap/src/style/SSE.css
Labels: FE, fix

#63 fix: 상세페이지 상품에 창고아이디 포함 및 SSE NGINX 설정
  be/build.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/asap/be/domain/notification/Notification.java
  be/src/main/java/asap/be/dto/DetailProductDto.java
  be/src/main/java/asap/be/dto/DetailWarehouseDto.java
  be/src/main/java/asap/be/facade/RedissonLockServiceFacade.java
  be/src/main/java/asap/be/repository/EmitterRepository.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/controller/NotificationRestDocs.java
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/controller/WarehouseRestDocs.java
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/WarehouseRepositoryTest.java
Labels: bug, BE, fix

#68 feat: S3 image upload and QRcode maker
  be/build.gradle
  be/src/main/java/asap/be/config/RedisConfig.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/qrcode/ImageConfig.java
  be/src/main/java/asap/be/qrcode/QrcodeController.java
  be/src/main/java/asap/be/qrcode/QrcodeGeneratorService.java
  be/src/main/java/asap/be/qrcode/S3UploadService.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
Labels: enhancement, BE

#70 fix: s3 bucket change, add contentType, 미사용 import문 제거
  be/src/main/java/asap/be/qrcode/QrcodeController.java
  be/src/main/java/asap/be/qrcode/QrcodeGeneratorService.java
  be/src/main/java/asap/be/qrcode/S3UploadService.java
  be/src/main/resources/application.yml
Labels: BE
