Repository mskim0425/asap, pull requests merged in 2023-03, with the labels that each got.

#6 #5 feat: basic settings
  .idea/workspace.xml
  be/.gradle/7.6.1/checksums/checksums.lock
  be/.gradle/7.6.1/checksums/md5-checksums.bin
  be/.gradle/7.6.1/checksums/sha1-checksums.bin
  be/.gradle/7.6.1/dependencies-accessors/dependencies-accessors.lock
  be/.gradle/7.6.1/dependencies-accessors/gc.properties
  be/.gradle/7.6.1/executionHistory/executionHistory.bin
  be/.gradle/7.6.1/executionHistory/executionHistory.lock
  be/.gradle/7.6.1/fileChanges/last-build.bin
  be/.gradle/7.6.1/fileHashes/fileHashes.bin
  be/.gradle/7.6.1/fileHashes/fileHashes.lock
  be/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  be/.gradle/7.6.1/gc.properties
  be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  be/.gradle/buildOutputCleanup/cache.properties
  be/.gradle/buildOutputCleanup/outputFiles.bin
  be/.gradle/file-system.probe
  be/.gradle/vcs-1/gc.properties
  be/.idea/.gitignore
  be/.idea/compiler.xml
  be/.idea/gradle.xml
  be/.idea/jarRepositories.xml
  be/.idea/jpa-buddy.xml
  be/.idea/misc.xml
  be/.idea/vcs.xml
  be/build.gradle
  be/build/resources/main/application.properties
  be/build/tmp/compileJava/previous-compilation-data.bin
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/Product.java
  be/src/main/java/asap/be/domain/Release.java
  be/src/main/java/asap/be/domain/Stock.java
  be/src/main/java/asap/be/domain/Warehouse.java
  be/src/main/java/asap/be/dto/ReleaseStockDto.java
  be/src/main/java/asap/be/repository/ProductMapper.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseMapper.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/WarehouseMapper.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/ProductMapper.xml
  be/src/main/resources/asap/be/repository/ReleaseMapper.xml
  be/src/main/resources/asap/be/repository/Warehouse.xml
Labels: enhancement, BE

#7 feat: 230329 merge
  asap/package-lock.json
  asap/package.json
  asap/src/App.js
  asap/src/Pages/Dashboard.css
  asap/src/Pages/Dashboard.js
  asap/src/component/Chart/Chart1.js
  asap/src/component/Chart/Chart2.js
  asap/src/component/Sidebar.css
  asap/src/style.css
Labels: FE

#13 feat: CRUD 추가 및 테스트 코드 진행
  be/.gitignore
  be/.gradle/7.6.1/checksums/checksums.lock
  be/.gradle/7.6.1/checksums/md5-checksums.bin
  be/.gradle/7.6.1/checksums/sha1-checksums.bin
  be/.gradle/7.6.1/executionHistory/executionHistory.bin
  be/.gradle/7.6.1/executionHistory/executionHistory.lock
  be/.gradle/7.6.1/fileHashes/fileHashes.bin
  be/.gradle/7.6.1/fileHashes/fileHashes.lock
  be/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  be/.gradle/buildOutputCleanup/outputFiles.bin
  be/.gradle/file-system.probe
  be/.idea/.gitignore
  be/build.gradle
  be/build/reports/tests/test/classes/asap.be.domain.ProductRepositoryTest.html
  be/build/reports/tests/test/index.html
  be/build/reports/tests/test/packages/asap.be.domain.html
  be/build/resources/main/application.yml
  be/build/resources/main/asap/be/repository/mybatis/ProductMapper.xml
  be/build/resources/main/asap/be/repository/mybatis/ReleaseMapper.xml
  be/build/resources/test/application.yml
  be/build/test-results/test/TEST-asap.be.domain.ProductRepositoryTest.xml
  be/build/test-results/test/binary/output.bin
  be/build/test-results/test/binary/output.bin.idx
  be/build/test-results/test/binary/results.bin
  be/build/tmp/compileJava/compileTransaction/stash-dir/MainController.class.uniqueId0
  be/build/tmp/compileJava/previous-compilation-data.bin
  be/build/tmp/compileTestJava/compileTransaction/stash-dir/ProductRepositoryTest.class.uniqueId0
  be/build/tmp/compileTestJava/previous-compilation-data.bin
  be/src/main/java/asap/be/aop/ForUpdate.java
  be/src/main/java/asap/be/aop/UpdateAspect.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/Product.java
  be/src/main/java/asap/be/dto/ProductDto.java
  be/src/main/java/asap/be/dto/RequestDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/search/SearchCond.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/application.yml
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/java/resources/application.yml
  be/src/test/resources/application.yml
Labels: bug, enhancement, BE

#14 feat: query change + dto
  be/.gitignore
  be/build/resources/main/asap/be/repository/mybatis/ProductMapper.xml
  be/build/resources/main/asap/be/repository/mybatis/ReleaseMapper.xml
  be/build/resources/main/asap/be/repository/mybatis/WarehouseMapper.xml
  be/build/resources/test/application.yml
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/Stock.java
  be/src/main/java/asap/be/dto/EverythingDto.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/WarehouseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMapper.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/service/WarehouseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/main/resources/asap/be/repository/mybatis/WarehouseMapper.xml
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/domain/ReleaseRepositoryTest.java
  be/src/test/resources/application.yml
Labels: bug, BE

#15 feat: pInsert 값 추가와 테스트 코드 수정
  be/.gitignore
  be/build/reports/tests/test/css/base-style.css
  be/build/reports/tests/test/css/style.css
  be/build/reports/tests/test/index.html
  be/build/reports/tests/test/js/report.js
  be/build/reports/tests/test/packages/asap.be.domain.html
  be/build/resources/main/application.yml
  be/build/resources/main/asap/be/repository/mybatis/ProductMapper.xml
  be/build/resources/main/asap/be/repository/mybatis/ReleaseMapper.xml
  be/build/resources/main/asap/be/repository/mybatis/WarehouseMapper.xml
  be/build/resources/test/application.yml
  be/build/test-results/test/binary/output.bin
  be/build/test-results/test/binary/output.bin.idx
  be/build/test-results/test/binary/results.bin
  be/build/tmp/compileJava/previous-compilation-data.bin
  be/build/tmp/compileTestJava/previous-compilation-data.bin
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/domain/Stock.java
  be/src/main/java/asap/be/dto/EverythingDto.java
  be/src/main/java/asap/be/repository/ReleaseRepository.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMapper.java
  be/src/main/java/asap/be/repository/mybatis/ReleaseMybatisRepository.java
  be/src/main/java/asap/be/service/ReleaseService.java
  be/src/main/java/asap/be/service/ReleaseServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
Labels: bug, BE
