Repository mskim0425/asap, pull requests merged in 2023-05, with the labels that each got.

#84 fix: SSE 503 에러 방지 더미데이터 타입 JSON으로 변경
  be/src/main/java/asap/be/domain/notification/NotificationType.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
Labels: BE, fix

#88 fix: remove sse header
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
Labels: BE

#89 fix: QRcode image URL 수정과 code 수정
  be/src/main/java/asap/be/config/MybatisConfig.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/PostProductDto.java
  be/src/main/java/asap/be/facade/RedissonLockServiceFacade.java
  be/src/main/java/asap/be/qrcode/QrcodeController.java
  be/src/main/java/asap/be/qrcode/QrcodeGeneratorService.java
  be/src/main/java/asap/be/qrcode/S3UploadService.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
Labels: BE, fix

#90 fix: 출고 랭킹 null
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
Labels: BE, fix

#92 fix: sse
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
Labels: BE, fix

#95 feat: 회원가입, 로그인 구현
  be/src/main/java/asap/be/BeApplication.java
  be/src/main/java/asap/be/config/MybatisConfig.java
  be/src/main/java/asap/be/config/RedisConfig.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/controller/MainV2Controller.java
  be/src/main/java/asap/be/domain/Member.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/facade/RedissonLockServiceFacade.java
  be/src/main/java/asap/be/repository/MemberRepository.java
  be/src/main/java/asap/be/repository/mybatis/EmitterMybatisRepository.java
  be/src/main/java/asap/be/repository/mybatis/MemberMapper.java
  be/src/main/java/asap/be/repository/mybatis/MemberMybatisRepository.java
  be/src/main/java/asap/be/service/MemberService.java
  be/src/main/java/asap/be/service/MemberServiceImpl.java
  be/src/main/java/asap/be/service/NotificationService.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/asap/be/repository/mybatis/MemberMapper.xml
  be/src/test/java/asap/be/controller/NotificationRestDocs.java
Labels: BE

#91 fix: SSE 하나씩 보여주기
  asap/src/Component/SSE.js
  asap/src/Pages/Dashboard.jsx
  asap/src/index.js
  asap/src/style/Dashboard.css
  asap/src/style/SSE.css
  asap/src/style/style.css
Labels: FE, fix

#98 fix: 비동기 기능 활성화
  be/src/main/java/asap/be/config/AsyncConfig.java
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/controller/MainV2Controller.java
  be/src/main/java/asap/be/qrcode/QrcodeController.java
  be/src/main/java/asap/be/qrcode/QrcodeGeneratorService.java
  be/src/main/java/asap/be/qrcode/S3UploadService.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/WarehouseMybatisRepository.java
  be/src/main/java/asap/be/service/DashBoardService.java
  be/src/main/java/asap/be/service/DashBoardServiceImpl.java
  be/src/main/java/asap/be/service/MailService.java
  be/src/main/java/asap/be/service/MailServiceImpl.java
  be/src/main/java/asap/be/service/NotificationServiceImpl.java
  be/src/main/java/asap/be/service/ProductService.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/java/asap/be/service/WarehouseService.java
  be/src/main/java/asap/be/utils/RedisUtil.java
  be/src/main/resources/application.yml
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/domain/ConcurrencyTest.java
Labels: BE, fix

#99 feat: signin & signup
  asap/package-lock.json
  asap/package.json
  asap/src/App.js
  asap/src/Component/Header/Header.jsx
  asap/src/Component/Sign/SignIn.jsx
  asap/src/Component/Sign/SignUp.jsx
  asap/src/Pages/Sign.jsx
  asap/src/style/Sign.css
Labels: FE, style

#101 fix: 약간의 버그 및 메일 형식 수정
  be/src/main/java/asap/be/controller/MainV2Controller.java
  be/src/main/java/asap/be/exception/ExceptionCode.java
  be/src/main/java/asap/be/service/MailServiceImpl.java
Labels: BE, fix

#104 fix: 무한스크롤 limit 10 -> 30, 일일 입고량 오류 해결
  be/src/main/java/asap/be/config/MailConfig.java
  be/src/main/java/asap/be/repository/ProductRepository.java
  be/src/main/java/asap/be/repository/mybatis/ProductMapper.java
  be/src/main/java/asap/be/repository/mybatis/ProductMybatisRepository.java
  be/src/main/resources/asap/be/repository/mybatis/ProductMapper.xml
Labels: bug, BE, fix

#105 feat: 로그인 및 회원가입 테스트코드 작성, 테스트 통과 안되던 로직 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/asap/be/controller/MainController.java
  be/src/main/java/asap/be/dto/EditProductDto.java
  be/src/main/java/asap/be/dto/MailDto.java
  be/src/main/java/asap/be/service/ProductServiceImpl.java
  be/src/main/resources/static/docs/index.html
  be/src/test/java/asap/be/controller/DashboardRestDocs.java
  be/src/test/java/asap/be/controller/MemberRestDocs.java
  be/src/test/java/asap/be/controller/ProductRestDocs.java
  be/src/test/java/asap/be/controller/ReleaseRestDocs.java
  be/src/test/java/asap/be/controller/WarehouseRestDocs.java
  be/src/test/java/asap/be/domain/ProductRepositoryTest.java
  be/src/test/java/asap/be/utils/MainV2ControllerConstants.java
Labels: enhancement, BE

#106 feat: login 상태 추가 & logout 기능 추가
  asap/package-lock.json
  asap/package.json
  asap/src/App.js
  asap/src/Component/Header/Header.jsx
  asap/src/Component/Sign/SignIn.jsx
  asap/src/Pages/Sign.jsx
  asap/src/index.js
  asap/src/routes/index.jsx
  asap/src/state/atoms.js
Labels: FE

#110 fix: 입고 sort SUM 추가
  be/src/main/resources/asap/be/repository/mybatis/ReleaseMapper.xml
Labels: BE
